# Generated by Django 4.1.7 on 2023-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания записи"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Время обновления записи"
                    ),
                ),
                (
                    "resume_ref",
                    models.URLField(max_length=255, verbose_name="Ссылка на резюме"),
                ),
                (
                    "github_ref",
                    models.URLField(max_length=255, verbose_name="Ссылка на GitHub"),
                ),
                (
                    "email",
                    models.EmailField(max_length=255, verbose_name="Email адресс"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
    ]
