# Generated by Django 4.1.7 on 2023-03-08 17:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="detail_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="Выполненная работа",
                help_text="Детальное описание выполненной работы",
                max_length=512,
                verbose_name="Детальное описание",
            ),
        ),
    ]
